### PR TITLE
Add course and contributors

### PR DESCRIPTION
**Pull request by DruhanShah**

### CODE REVIEW

**Review by b-beri — CHANGES_REQUESTED** [review]
Please once update your files before pushing changes. So kindly once check for any new recent changes in the about.html file. 
Also, update the total number of contributors one below contributors list.

**Review by b-beri — APPROVED** [review]

**Comment by b-beri** [comment]
In Links, please check them once.

**Comment by b-beri** [comment]
ITL-1 Link was wrong

**Comment by DruhanShah** [comment]
Ah, mb. Fixed that in my fork too

**Pull request merged**
